dist: trusty
language: java
jdk:
  - oraclejdk8  # Legacy
  - oraclejdk11 # LTS
  - oraclejdk15 # Latest
jobs:
  include:
    # Extra job, testing legacy CMM option
    - jdk: oraclejdk8
      env: MAVEN_OPTS=-Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
cache:
  directories:
  - $HOME/.m2
